name: pcl-docs

channels:
- !!python/unicode
  'conda-forge'
  # - anaconda

dependencies:
  - python>=3.6
  # 2.1.x exhale ng?
  - Sphinx==2.0
  - doxygen
  - boost-cpp
  - eigen
  - flann=1.9.1
  - qhull=2015.2
  - vtk=8.2.0
  #- cmake==3.13
  - breathe>=4.13.0
  - sphinx_rtd_theme 
  # - mesalib
  # - glfw
  # - freeglut
  # - mesa-libgl-cos6-x86_64
  - pip
  - pip:
    # breathe extension(Automatic C++ library API documentation generator)
    - cmake==3.13
    - exhale
    #- sphinx-rtd-theme
