name: pcl-docs

channels:
  - conda-forge

dependencies:
  - python>=3.6
  - Sphinx>=2.0
  - cmake
  - doxygen
  # tex
  # - miktex [win]
  # patch
  - m2-patch [win]
  # pcl build packages
  - boost=1.69
  - eigen=3.3
  - flann=1.9.1
  - qhull=2015.2
  - vtk=8.2.0
  - pip:
    - cmake
    - breathe>=4.13.0
    # breathe extension?
    # - exhale
    - sphinx-rtd-theme
    # doxylink?
    # - sphinxcontrib-doxylink
