name: pcl-docs

channels:
  - 'conda-forge'

dependencies:
  - python>=3.6
  # 2.1.x exhale ng?
  - Sphinx==2.0
  - doxygen
  - boost-cpp
  - eigen
  - flann=1.9.1
  - qhull=2015.2
  - vtk=8.2.0
  - scikit-build
  - cmake>=3.13
  - breathe>=4.13.0
  - sphinx_rtd_theme 
  # - mesalib
  # - glfw
  # - freeglut
  # - mesa-libgl-cos6-x86_64
  - pip
  - pip:
    # breathe extension(Automatic C++ library API documentation generator)
    # - breathe>=4.13.0
    # depend scikit-build
    - cmake>=3.13
    - exhale
    #- sphinx-rtd-theme
