name: pcl-docs

channels:
  - conda-forge

dependencies:
  - python>=3.6
  - Sphinx>=2.0
  # binary only?
  # - cmake==3.13.3
  - doxygen
  # tex
  # - miktex [win]
  # patch
  # - m2-patch [win]
  # pcl build packages
  # - boost=1.69
  - boost-cpp
  - eigen
  - flann=1.9.1
  - qhull=2015.2
  - vtk=8.2.0
  - pip:
    - cmake==3.13.3
    - breathe>=4.13.0
    # breathe extension(Automatic C++ library API documentation generator)
    - exhale
    - sphinx-rtd-theme
    # doxylink?
    # - sphinxcontrib-doxylink
