name: pcl-docs

channels:
- !!python/unicode
  'conda-forge'
  # - anaconda

dependencies:
  - python>=3.6
  - doxygen
  - boost-cpp
  - eigen
  - flann=1.9.1
  - qhull=2015.2
  - vtk=8.2.0
  - scikit-build
  #- cmake>=3.13
  #- Sphinx>=2.0
  #- breathe>=4.13.0
  #- sphinx_rtd_theme
  # - mesalib
  # - glfw
  # - freeglut
  # - mesa-libgl-cos6-x86_64
  # Using Pip in a Conda Environment
  - pip
  - pip:
    - cmake>=3.13
    # breathe extension(Automatic C++ library API documentation generator)
    - Sphinx>=2.0
    - breathe>=4.13.0
    - exhale
    - sphinx-rtd-theme
    - git+https://github.com/readthedocs/readthedocs-sphinx-search@master
