name: pcl-docs

channels:
  - conda-forge

dependencies:
  - python>=3.6
  - Sphinx
  - cmake
  - doxygen
  # - miktex [win]
  # pcl build packages
  - boost=1.69
  - eigen=3.3
  - flann=1.9.1
  - qhull
  - vtk=8.1.2
  - pip:
    - cmake
    - breathe
    - sphinx-rtd-theme
